#!/bin/sh

/usr/bin/changeinstalld "uninstall"

launchctl unload /System/Library/LaunchDaemons/com.apple.mobile.installd.plist
launchctl load /System/Library/LaunchDaemons/com.apple.mobile.installd.plist

echo Start Uninstall!
